server:
 port: 8081

spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbuy
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /Hplus-v.4.1.0
      suffix:
  devtools:
    restart:
      exclude: static/**

mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.java.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
