server:
  port: 8080

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  routes:  #配置服务名和虚拟路径 spring.applicatin.name    虚拟路径
    admin: /admin/***  #admin开头的，找hb-admin
    web: /web/***  #admin开头的，找hb-admin
