server:
 port: 8082

spring:
  application:
    name: web
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/hbuy
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: druid
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /pages/
      suffix:
  redis:
    database: 0
    host: 127.0.0.1
    timeout: 3000
    port: 6379
  devtools:
    restart:
      exclude: static/**

mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: com.java.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
